---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  This is the Cloud formation template to configure kinesis firehose to stream data from kinesis stream and put in S3 bucket.

#Metadata:

Parameters:
  creator:
    Description: 'Creator tag to be used in resources'
    Type: String
    Default: gowrish
  projectName:
    Description: 'Project tag to be used in resources'
    Type: String
    Default: ProjectTag
  environment:
    Description: Environment
    Type: String
    Default: dev
  kinesisSourceStreamName:
    Type: String
    Default: ${project-name}-events-stream-dev
  kinesisFirehoseDeliveryStreamName:
    Type: String
    Default: ${project-name}-kinesis-firehose-es-delivery-stream
  elasticSearcDomainName:
    Type: String
    Default: ${project-name}-events-dev
  s3StackName:
    Type: String
    Default: s3-dev         # Stack name used to create s3 bucket. Sample format for name :- ${project-s3-environment}
  kinesisStackName:
    Type: String
    Default: kinesis-dev    # Stack name used to create Kinesis stream. Sample format for name :- ${project-kinesis-environment}
  logsRetentionDays:
    Type: Number
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  nodesForEsDomain:
    Type: Number
    Description: number of data nodes for Elastic Search Domain
    Default: 2
    MinValue: 2
    MaxValue: 3
  eSInstanceType:
    Type: String
    Description: "Instance Type for ES Domain Refer: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-instance-types.html"
  encryptionAtRest:
    Type: String
    Description: Whether the domain should encrypt data at rest,
    AllowedValues: ['true','false']
  azCount:
    Type: String
    Description: The number of AZs that you want the domain to use.
    AllowedValues: [2,3]
  ebsSizeForEs:
    Type: String
    Description: "The size (in GiB) of the EBS volume for each data node. Refer: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html"
    Default: 10
  esIndexRotation:
    Type: String
    Description: "The frequency of Elasticsearch index rotation. If you enable index rotation, Kinesis Data Firehose appends a portion of the UTC arrival timestamp to the specified index name, and rotates the appended timestamp accordingly"
    AllowedValues: ['NoRotation', 'OneHour', 'OneDay', 'OneWeek', 'OneMonth']
    Default: OneMonth
#Conditions:

Resources:
  # Log delivery group for fiehose
  firehoseDeliveryLogGrp:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/firehose/${project-name}-${environment}"
      RetentionInDays: !Ref logsRetentionDays
  # Log delivery group for ElasticSearch
  elasticSearchLogGrp:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/elasticsearch/${project-name}-${environment}"
      RetentionInDays: !Ref logsRetentionDays

  # Creating Source Kinesis stream
  kinesisSourceStream:
    Type: AWS::Kinesis::Stream
    Properties:
        Name: !Ref kinesisSourceStreamName
        RetentionPeriodHours: 24
        ShardCount: 1
        StreamEncryption:
          EncryptionType: KMS
          KeyId: "alias/aws/kinesis"
        Tags:
          -
            Key: project
            Value: !Sub "${projectName}"
          -
            Key: creator
            Value: !Sub "${creator}"

  # Creating Iam role for delivery stream firehose
  firehoseDeliveryIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Action: sts:AssumeRole
          Condition: {}
      Path: /
      Policies:
      - PolicyName: Allow
        PolicyDocument:
          Statement:
          -
            Effect: "Allow"
            Action:
              - "kinesis:*"
            Resource:
              - !GetAtt kinesisSourceStream.Arn
          -
            Effect: "Allow"
            Action:
              - "s3:*"
            Resource:
              - Fn::ImportValue: !Sub ${s3StackName}-FirehoseBackupBucket
              -
                "Fn::Join":
                - ''
                - - !ImportValue
                      "Fn::Sub": "${s3StackName}-FirehoseBackupBucket"
                  - '/*'
          -
            Effect: Allow
            Action:
            - kms:*
            - es:*
            Resource:
            - '*'

  # Creating Firhose Kinesis stream:
  kinesisFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - firehoseDeliveryIAMRole
      - elasticsearchDomain
      - kinesisSourceStream
      - firehoseDeliveryLogGrp
      - elasticSearchLogGrp
    Properties:
      DeliveryStreamName: !Ref  kinesisFirehoseDeliveryStreamName
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt kinesisSourceStream.Arn
        RoleARN:
          Fn::GetAtt: [firehoseDeliveryIAMRole, Arn]
      ElasticsearchDestinationConfiguration:
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 15
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref firehoseDeliveryLogGrp
          LogStreamName: events-es-delivery
        DomainARN:  !GetAtt elasticsearchDomain.DomainArn
        IndexName: events
        IndexRotationPeriod: !Ref esIndexRotation
        RetryOptions:
          DurationInSeconds: 60
        RoleARN:
          Fn::GetAtt: [firehoseDeliveryIAMRole, Arn]
        S3BackupMode: AllDocuments
        S3Configuration:
          BucketARN:
            Fn::ImportValue: !Sub ${s3StackName}-FirehoseBackupBucket
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 1
          CompressionFormat: UNCOMPRESSED
          RoleARN:
            Fn::GetAtt: [firehoseDeliveryIAMRole, Arn]
        TypeName: ""

  # Creating Elastic search
  elasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '7.4'
      ElasticsearchClusterConfig:
        InstanceCount: !Ref nodesForEsDomain
        InstanceType: !Ref eSInstanceType
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: !Ref azCount
      DomainName: !Ref elasticSearcDomainName
      EncryptionAtRestOptions:
        Enabled: !Ref encryptionAtRest
        KmsKeyId: alias/aws/es
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: !Ref ebsSizeForEs
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AdvancedOptions:
        indices.fielddata.cache.size: 40
        rest.action.multi.allow_explicit_index: 'true'
      LogPublishingOptions:
        SEARCH_SLOW_LOGS:
          Enabled: true
          CloudWatchLogsLogGroupArn: !GetAtt elasticSearchLogGrp.Arn
        INDEX_SLOW_LOGS:
          Enabled: true
          CloudWatchLogsLogGroupArn: !GetAtt elasticSearchLogGrp.Arn
        ES_APPLICATION_LOGS:
          Enabled: true
          CloudWatchLogsLogGroupArn: !GetAtt elasticSearchLogGrp.Arn
      Tags:
        -
          Key: project
          Value: !Sub "${projectName}"
        -
          Key: creator
          Value: !Sub "${creator}"
        -
          Key: Name
          Value: !Sub "${projectName}-events-es-${environment}"


# Outputs:
